---
layout: "`r paste0("default_",region_to_report)`"
title:  Hunger dimensions
group: "`r paste0("page_",region_to_report)`"
---

`r paste0('<div class="page-header"><h2 id="">',region_name,'</h2></div>')`

<!--
%
% PPPPPPPPPPPPPPPPP                                               tttt           222222222222222
% P::::::::::::::::P                                           ttt:::t          2:::::::::::::::22
% P::::::PPPPPP:::::P                                          t:::::t          2::::::222222:::::2
% PP:::::P     P:::::P                                         t:::::t          2222222     2:::::2
%   P::::P     P:::::Paaaaaaaaaaaaa  rrrrr   rrrrrrrrr   ttttttt:::::ttttttt                2:::::2
%   P::::P     P:::::Pa::::::::::::a r::::rrr:::::::::r  t:::::::::::::::::t                2:::::2
%   P::::PPPPPP:::::P aaaaaaaaa:::::ar:::::::::::::::::r t:::::::::::::::::t             2222::::2
%   P:::::::::::::PP           a::::arr::::::rrrrr::::::rtttttt:::::::tttttt        22222::::::22
%   P::::PPPPPPPPP      aaaaaaa:::::a r:::::r     r:::::r      t:::::t            22::::::::222
%   P::::P            aa::::::::::::a r:::::r     rrrrrrr      t:::::t           2:::::22222
%   P::::P           a::::aaaa::::::a r:::::r                  t:::::t          2:::::2
%   P::::P          a::::a    a:::::a r:::::r                  t:::::t    tttttt2:::::2
% PP::::::PP        a::::a    a:::::a r:::::r                  t::::::tttt:::::t2:::::2       222222
% P::::::::P        a:::::aaaa::::::a r:::::r                  tt::::::::::::::t2::::::2222222:::::2
% P::::::::P         a::::::::::aa:::ar:::::r                    tt:::::::::::tt2::::::::::::::::::2
% PPPPPPPPPP          aaaaaaaaaa  aaaarrrrrrr                      ttttttttttt  22222222222222222222
%


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% PART2 - Hunger dimensions
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 -->

```{r setup-code-part2}
knitr::read_chunk(paste0(root.dir,"input/code/code_part2.R"))
```



```{r part2_setup, eval=include_part2}
```


<!-- %   _   _             _                                         _       _                              _
%  | | | | _ __    __| |  ___  _ __  _ __    ___   _   _  _ __ (_) ___ | |__   _ __ ___    ___  _ __  | |_
%  | | | || '_ \  / _` | / _ \| '__|| '_ \  / _ \ | | | || '__|| |/ __|| '_ \ | '_ ` _ \  / _ \| '_ \ | __|
%  | |_| || | | || (_| ||  __/| |   | | | || (_) || |_| || |   | |\__ \| | | || | | | | ||  __/| | | || |_
%   \___/ |_| |_| \__,_| \___||_|   |_| |_| \___/  \__,_||_|   |_||___/|_| |_||_| |_| |_| \___||_| |_| \__|
 -->


```{r P2undernuTEXT, eval=P2undernu, short_text_ChartPage=P2undernu}
```


```{r P2undernuData,results='hide', cache=FALSE}
```



```{r P2undernuTOPRIGHT, eval=P2undernu, top_right_minitable=P2undernu}
```


```{r P2undernuLEFT, eval=P2undernu, left_plot=P2undernu, fig.height=left_plot_height, fig.width=left_plot_width}
```

```{r P2undernuRIGHT, eval=P2undernu ,right_plot=P2undernu, fig.height=right_plot_height, fig.width=right_plot_width}
```


```{r P2undernuBOTTOM, eval=P2undernu, bottom_plot=P2undernu, fig.height=bottom_plot_height, fig.width=bottom_plot_width}
```


```{r P2undernuMAP, eval=P2undernu, map_plot=P2undernu, fig.width=map_plot_width, fig.height= map_plot_height}
```






<!-- %   _____                       _                             _   _           _       _   _   _   _
%  |  ___|   ___     ___     __| |     __ _  __   __   __ _  (_) | |   __ _  | |__   (_) | | (_) | |_   _   _
%  | |_     / _ \   / _ \   / _` |    / _` | \ \ / /  / _` | | | | |  / _` | | '_ \  | | | | | | | __| | | | |
%  |  _|   | (_) | | (_) | | (_| |   | (_| |  \ V /  | (_| | | | | | | (_| | | |_) | | | | | | | | |_  | |_| |
%  |_|      \___/   \___/   \__,_|    \__,_|   \_/    \__,_| |_| |_|  \__,_| |_.__/  |_| |_| |_|  \__|  \__, |
%                                                                                                       |___/ -->






```{r P2availabTEXT, eval=P2availab, short_text_ChartPage=P2availab}
```


```{r P2availabData, cache=FALSE,results='hide', eval=P2availab}
```



```{r P2availabTOPRIGHT, eval=P2availab, top_right_plot=P2availab, fig.height=top_right_plot_height, fig.width=top_right_plot_width}
```


```{r P2availabLEFT, eval=P2availab, left_plot=P2availab, fig.height=left_plot_height, fig.width=left_plot_width}
```

```{r P2availabRIGHT, eval=P2availab ,right_plot=P2availab, fig.height=right_plot_height, fig.width=right_plot_width}
```


```{r P2availabBOTTOM, eval=P2availab, bottom_plot=P2availab, fig.height=bottom_plot_height, fig.width=bottom_plot_width}
```


```{r P2availabMAP, eval=P2availab, map_plot=P2availab, fig.width=map_plot_width, fig.height= map_plot_height}
```





<!-- %   _____                       _
%  |  ___|   ___     ___     __| |     __ _    ___    ___    ___   ___   ___
%  | |_     / _ \   / _ \   / _` |    / _` |  / __|  / __|  / _ \ / __| / __|
%  |  _|   | (_) | | (_) | | (_| |   | (_| | | (__  | (__  |  __/ \__ \ \__ \
%  |_|      \___/   \___/   \__,_|    \__,_|  \___|  \___|  \___| |___/ |___/
% -->





```{r P2accessTEXT, eval=P2access, short_text_ChartPage=P2access}
```


```{r P2accessData, cache=FALSE,results='hide', eval=P2access}
```



```{r P2accessTOPRIGHT, eval=P2access, top_right_plot=P2access, fig.height=top_right_plot_height, fig.width=top_right_plot_width}
```


```{r P2accessLEFT, eval=P2access, left_plot=P2access, fig.height=left_plot_height, fig.width=left_plot_width}
```

```{r P2accessRIGHT, eval=P2access ,right_plot=P2access, fig.height=right_plot_height, fig.width=right_plot_width}
```


```{r P2accessBOTTOM, eval=P2access, bottom_plot=P2access, fig.height=bottom_plot_height, fig.width=bottom_plot_width}
```


```{r P2accessMAP, eval=P2access, map_plot=P2access, fig.width=map_plot_width, fig.height= map_plot_height}
```



<!-- %   _____                       _           _             _       _   _   _   _
%  |  ___|   ___     ___     __| |    ___  | |_    __ _  | |__   (_) | | (_) | |_   _   _
%  | |_     / _ \   / _ \   / _` |   / __| | __|  / _` | | '_ \  | | | | | | | __| | | | |
%  |  _|   | (_) | | (_) | | (_| |   \__ \ | |_  | (_| | | |_) | | | | | | | | |_  | |_| |
%  |_|      \___/   \___/   \__,_|   |___/  \__|  \__,_| |_.__/  |_| |_| |_|  \__|  \__, |
%                                                                                   |___/ -->


```{r P2stabilityTEXT, eval=P2stability, short_text_ChartPage=P2stability}
```


```{r P2stabilityData, cache=FALSE,results='hide', eval=P2stability}
```



```{r P2stabilityTOPRIGHT, eval=P2stability, top_right_plot=P2stability, fig.height=top_right_plot_height, fig.width=top_right_plot_width}
```


```{r P2stabilityLEFT, eval=P2stability, left_plot=P2stability, fig.height=left_plot_height, fig.width=left_plot_width}
```

```{r P2stabilityRIGHT, eval=P2stability ,right_plot=P2stability, fig.height=right_plot_height, fig.width=right_plot_width}
```


```{r P2stabilityBOTTOM, eval=P2stability, bottom_plot=P2stability, fig.height=bottom_plot_height, fig.width=bottom_plot_width}
```


```{r P2stabilityMAP, eval=P2stability, map_plot=P2stability, fig.width=map_plot_width, fig.height= map_plot_height}
```


<!-- %   _____                       _             _     _   _   _                 _     _
%  |  ___|   ___     ___     __| |    _   _  | |_  (_) | | (_)  ____   __ _  | |_  (_)   ___    _ __
%  | |_     / _ \   / _ \   / _` |   | | | | | __| | | | | | | |_  /  / _` | | __| | |  / _ \  | '_ \
%  |  _|   | (_) | | (_) | | (_| |   | |_| | | |_  | | | | | |  / /  | (_| | | |_  | | | (_) | | | | |
%  |_|      \___/   \___/   \__,_|    \__,_|  \__| |_| |_| |_| /___|  \__,_|  \__| |_|  \___/  |_| |_|
% -->


```{r P2utilizaTEXT, eval=P2utiliza, short_text_ChartPage=P2utiliza}
```


```{r P2utilizaData, cache=FALSE,results='hide', eval=P2utiliza}
```


```{r P2utilizaTOPRIGHT, eval=P2utiliza, top_right_minitable=P2utiliza}
```


```{r P2utilizaLEFT, eval=P2utiliza, left_plot=P2utiliza, fig.height=left_plot_height, fig.width=left_plot_width}
```

```{r P2utilizaRIGHT, eval=P2utiliza ,right_plot=P2utiliza, fig.height=right_plot_height, fig.width=right_plot_width}
```


```{r P2utilizaBOTTOM, eval=P2utiliza, bottom_plot=P2utiliza, fig.height=bottom_plot_height, fig.width=bottom_plot_width}
```


```{r P2utilizaMAP, eval=P2utiliza, map_plot=P2utiliza, fig.width=map_plot_width, fig.height= map_plot_height}
```

