---
layout: "`r paste0("default_",region_to_report)`"
title:  Coffee production, trade and prices
group: "`r paste0("page_",region_to_report)`"
---

`r paste0('<div class="page-header"><h2 id="">',region_name,'</h2></div>')`

<!-- % -->
<!-- % PPPPPPPPPPPPPPPPP                                               tttt                  66666666 -->
<!-- % P::::::::::::::::P                                           ttt:::t                 6::::::6 -->
<!-- % P::::::PPPPPP:::::P                                          t:::::t                6::::::6 -->
<!-- % PP:::::P     P:::::P                                         t:::::t               6::::::6 -->
<!-- %   P::::P     P:::::Paaaaaaaaaaaaa  rrrrr   rrrrrrrrr   ttttttt:::::ttttttt        6::::::6 -->
<!-- %   P::::P     P:::::Pa::::::::::::a r::::rrr:::::::::r  t:::::::::::::::::t       6::::::6 -->
<!-- %   P::::PPPPPP:::::P aaaaaaaaa:::::ar:::::::::::::::::r t:::::::::::::::::t      6::::::6 -->
<!-- %   P:::::::::::::PP           a::::arr::::::rrrrr::::::rtttttt:::::::tttttt     6::::::::66666 -->
<!-- %   P::::PPPPPPPPP      aaaaaaa:::::a r:::::r     r:::::r      t:::::t          6::::::::::::::66 -->
<!-- %   P::::P            aa::::::::::::a r:::::r     rrrrrrr      t:::::t          6::::::66666:::::6 -->
<!-- %   P::::P           a::::aaaa::::::a r:::::r                  t:::::t          6:::::6     6:::::6 -->
<!-- %   P::::P          a::::a    a:::::a r:::::r                  t:::::t    tttttt6:::::6     6:::::6 -->
<!-- % PP::::::PP        a::::a    a:::::a r:::::r                  t::::::tttt:::::t6::::::66666::::::6 -->
<!-- % P::::::::P        a:::::aaaa::::::a r:::::r                  tt::::::::::::::t 66:::::::::::::66 -->
<!-- % P::::::::P         a::::::::::aa:::ar:::::r                    tt:::::::::::tt   66:::::::::66 -->
<!-- % PPPPPPPPPP          aaaaaaaaaa  aaaarrrrrrr                      ttttttttttt       666666666 -->

<!-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %% PART6 - Coffee book coffee specific spreads! -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->


```{r setup-code-part6}
knitr::read_chunk(paste0(root.dir,"input/code/code_part6.R"))
```

```{r part6_setup, eval=include_part6}
```


<!-- % -->
<!-- %    ____            __    __                                              _                  _     _ -->
<!-- %   / ___|   ___    / _|  / _|   ___    ___     _ __    _ __    ___     __| |  _   _    ___  | |_  (_)   ___    _ __ -->
<!-- %  | |      / _ \  | |_  | |_   / _ \  / _ \   | '_ \  | '__|  / _ \   / _` | | | | |  / __| | __| | |  / _ \  | '_ \ -->
<!-- %  | |___  | (_) | |  _| |  _| |  __/ |  __/   | |_) | | |    | (_) | | (_| | | |_| | | (__  | |_  | | | (_) | | | | | -->
<!-- %   \____|  \___/  |_|   |_|    \___|  \___|   | .__/  |_|     \___/   \__,_|  \__,_|  \___|  \__| |_|  \___/  |_| |_| -->
<!-- %                                              |_| -->
<!-- % -->




```{r P6coffeeprodTEXT, eval=P6coffeeprod, short_text_ChartPage=P6coffeeprod}
```


```{r P6coffeeprodData, cache=FALSE,results='hide', eval=P6coffeeprod, cache=cache_part6}
```



```{r P6coffeeprodTOPRIGHT, eval=P6coffeeprod, top_right_minitable=P6coffeeprod}
```


```{r P6coffeeprodLEFT, eval=P6coffeeprod, left_plot=P6coffeeprod, fig.height=left_plot_height, fig.width=left_plot_width}
```

```{r P6coffeeprodRIGHT, eval=P6coffeeprod ,right_plot=P6coffeeprod, fig.height=right_plot_height, fig.width=right_plot_width}
```


```{r P6coffeeprodBOTTOM, eval=P6coffeeprod, bottom_plot=P6coffeeprod, fig.height=bottom_plot_height, fig.width=bottom_plot_width}
```


```{r P6coffeeprodMAP, eval=P6coffeeprod, map_plot=P6coffeeprod, fig.width=map_plot_width, fig.height= map_plot_height}
```




<!-- %    ____            __    __                   _                        _ -->
<!-- %   / ___|   ___    / _|  / _|   ___    ___    | |_   _ __    __ _    __| |   ___ -->
<!-- %  | |      / _ \  | |_  | |_   / _ \  / _ \   | __| | '__|  / _` |  / _` |  / _ \ -->
<!-- %  | |___  | (_) | |  _| |  _| |  __/ |  __/   | |_  | |    | (_| | | (_| | |  __/ -->
<!-- %   \____|  \___/  |_|   |_|    \___|  \___|    \__| |_|     \__,_|  \__,_|  \___| -->
<!-- % -->


```{r P6coffeetradeTEXT, eval=P6coffeetrade, short_text_ChartPage=P6coffeetrade}
```


```{r P6coffeetradeData, cache=FALSE,results='hide', eval=P6coffeetrade, cache=cache_part6}
```


```{r P6coffeetradeTOPRIGHT, eval=P6coffeetrade, top_right_minitable=P6coffeetrade}
```


```{r P6coffeetradeLEFT, eval=P6coffeetrade, left_plot=P6coffeetrade, fig.height=left_plot_height, fig.width=left_plot_width}
```

```{r P6coffeetradeRIGHT, eval=P6coffeetrade ,right_plot=P6coffeetrade, fig.height=right_plot_height, fig.width=right_plot_width}
```


```{r P6coffeetradeBOTTOM, eval=P6coffeetrade, bottom_plot=P6coffeetrade, fig.height=bottom_plot_height, fig.width=bottom_plot_width}
```


```{r P6coffeetradeMAP, eval=P6coffeetrade, map_plot=P6coffeetrade, fig.width=map_plot_width, fig.height= map_plot_height}
```




<!-- %    ____         __   __                            _ -->
<!-- %   / ___| ___   / _| / _|  ___   ___   _ __   _ __ (_)  ___  ___  ___ -->
<!-- %  | |    / _ \ | |_ | |_  / _ \ / _ \ | '_ \ | '__|| | / __|/ _ \/ __| -->
<!-- %  | |___| (_) ||  _||  _||  __/|  __/ | |_) || |   | || (__|  __/\__ \ -->
<!-- %   \____|\___/ |_|  |_|   \___| \___| | .__/ |_|   |_| \___|\___||___/ -->
<!-- %                                      |_| -->





```{r P6coffeepricesTEXT, eval=P6coffeeprices, short_text_ChartPage=P6coffeeprices}
```


```{r P6coffeepricesData, cache=FALSE,results='hide', eval=P6coffeeprices, cache=cache_part6}
```



```{r P6coffeepricesTOPRIGHT, eval=P6coffeeprices, top_right_plot=P6coffeeprices, fig.height=top_right_plot_height, fig.width=top_right_plot_width}
```


```{r P6coffeepricesLEFT, eval=P6coffeeprices, left_plot=P6coffeeprices, fig.height=left_plot_height, fig.width=left_plot_width}
```

```{r P6coffeepricesRIGHT, eval=P6coffeeprices ,right_plot=P6coffeeprices, fig.height=right_plot_height, fig.width=right_plot_width}
```


```{r P6coffeepricesBOTTOM, eval=P6coffeeprices, bottom_plot=P6coffeeprices, fig.height=bottom_plot_height, fig.width=bottom_plot_width}
```


```{r P6coffeepricesMAP, eval=P6coffeeprices, map_plot=P6coffeeprices, fig.width=map_plot_width, fig.height= map_plot_height}
```