---
layout: "`r paste0("default_",region_to_report)`"
title:  Food supply
group: "`r paste0("page_",region_to_report)`"
---

`r paste0('<div class="page-header"><h2 id="">',region_name,'</h2></div>')`

<!--
%
% PPPPPPPPPPPPPPPPP                                               tttt           333333333333333
% P::::::::::::::::P                                           ttt:::t          3:::::::::::::::33
% P::::::PPPPPP:::::P                                          t:::::t          3::::::33333::::::3
% PP:::::P     P:::::P                                         t:::::t          3333333     3:::::3
%   P::::P     P:::::Paaaaaaaaaaaaa  rrrrr   rrrrrrrrr   ttttttt:::::ttttttt                3:::::3
%   P::::P     P:::::Pa::::::::::::a r::::rrr:::::::::r  t:::::::::::::::::t                3:::::3
%   P::::PPPPPP:::::P aaaaaaaaa:::::ar:::::::::::::::::r t:::::::::::::::::t        33333333:::::3
%   P:::::::::::::PP           a::::arr::::::rrrrr::::::rtttttt:::::::tttttt        3:::::::::::3
%   P::::PPPPPPPPP      aaaaaaa:::::a r:::::r     r:::::r      t:::::t              33333333:::::3
%   P::::P            aa::::::::::::a r:::::r     rrrrrrr      t:::::t                      3:::::3
%   P::::P           a::::aaaa::::::a r:::::r                  t:::::t                      3:::::3
%   P::::P          a::::a    a:::::a r:::::r                  t:::::t    tttttt            3:::::3
% PP::::::PP        a::::a    a:::::a r:::::r                  t::::::tttt:::::t3333333     3:::::3
% P::::::::P        a:::::aaaa::::::a r:::::r                  tt::::::::::::::t3::::::33333::::::3
% P::::::::P         a::::::::::aa:::ar:::::r                    tt:::::::::::tt3:::::::::::::::33
% PPPPPPPPPP          aaaaaaaaaa  aaaarrrrrrr                      ttttttttttt   333333333333333
%



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% PART3 - Food Supply
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->



```{r setup-code-part3}
knitr::read_chunk(paste0(root.dir,"input/code/code_part3.R"))
```



```{r part3_setup, eval=include_part3}
```

<!--
%   ____   _        _                                                                                         _
%  |  _ \ (_)  ___ | |_  __ _  _ __  _   _    ___  _ __    ___  _ __  __ _  _   _   ___  _   _  _ __   _ __  | | _   _
%  | | | || | / _ \| __|/ _` || '__|| | | |  / _ \| '_ \  / _ \| '__|/ _` || | | | / __|| | | || '_ \ | '_ \ | || | | |
%  | |_| || ||  __/| |_| (_| || |   | |_| | |  __/| | | ||  __/| |  | (_| || |_| | \__ \| |_| || |_) || |_) || || |_| |
%  |____/ |_| \___| \__|\__,_||_|    \__, |  \___||_| |_| \___||_|   \__, | \__, | |___/ \__,_|| .__/ | .__/ |_| \__, |
%                                    |___/                           |___/  |___/              |_|    |_|        |___/ -->


```{r P3desTEXT, eval=P3des, short_text_ChartPage=P3des}
```

```{r P3desData,results='hide', cache=FALSE, eval=P3des}
```


```{r P3desTOPRIGHT, eval=P3des, top_right_plot=P3des, fig.height=top_right_plot_height, fig.width=top_right_plot_width}
```

```{r P3desLEFT, eval=P3des, left_plot=P3des, fig.height=left_plot_height, fig.width=left_plot_width}
```

```{r P3desRIGHT, eval=P3des ,right_plot=P3des, fig.height=right_plot_height, fig.width=right_plot_width}
```


```{r P3desBOTTOM, eval=P3des, bottom_plot=P3des, fig.height=bottom_plot_height, fig.width=bottom_plot_width}
```


```{r P3desMAP, eval=P3des, map_plot=P3des, fig.width=map_plot_width, fig.height= map_plot_height}
```





<!--
%    ____                                             _               _    _
%   / ___| _ __  ___   _ __    _ __   _ __  ___    __| | _   _   ___ | |_ (_)  ___   _ __
%  | |    | '__|/ _ \ | '_ \  | '_ \ | '__|/ _ \  / _` || | | | / __|| __|| | / _ \ | '_ \
%  | |___ | |  | (_) || |_) | | |_) || |  | (_) || (_| || |_| || (__ | |_ | || (_) || | | |
%   \____||_|   \___/ | .__/  | .__/ |_|   \___/  \__,_| \__,_| \___| \__||_| \___/ |_| |_|
%                     |_|     |_|
% -->



```{r P3cropproTEXT, eval=P3croppro, short_text_ChartPage=P3croppro}
```

```{r P3cropproData,results='hide', cache=FALSE, eval=P3croppro}
```

```{r P3cropproTOPRIGHT, eval=P3croppro, top_right_minitable=P3croppro}
```

```{r P3cropproLEFT, eval=P3croppro, left_plot=P3croppro, fig.height=left_plot_height, fig.width=left_plot_width}
```

```{r P3cropproRIGHT, eval=P3croppro ,right_plot=P3croppro, fig.height=right_plot_height, fig.width=right_plot_width}
```


```{r P3cropproBOTTOM, eval=P3croppro, bottom_plot=P3croppro, fig.height=bottom_plot_height, fig.width=bottom_plot_width}
```


```{r P3cropproMAP, eval=P3croppro, map_plot=P3croppro, fig.width=map_plot_width, fig.height= map_plot_height}
```


<!-- %
%    ____
%   / ___| _ __  ___   _ __
%  | |    | '__|/ _ \ | '_ \
%  | |___ | |  | (_) || |_) |
%   \____||_|   \___/ | .__/
%                     |_|
% -->



```{r P3cropTEXT, eval=P3crop, short_text_ChartPage=P3crop}
```

```{r P3cropData,results='hide',cache=FALSE,eval=P3crop}
```


```{r P3cropTOPRIGHT, eval=P3crop, top_right_minitable=P3crop}
```


```{r P3cropLEFT, eval=P3crop, left_plot=P3crop, fig.height=left_plot_height, fig.width=left_plot_width}
```

```{r P3cropRIGHT, eval=P3crop ,right_plot=P3crop, fig.height=right_plot_height, fig.width=right_plot_width}
```


```{r P3cropBOTTOM, eval=P3crop, bottom_plot=P3crop, fig.height=bottom_plot_height, fig.width=bottom_plot_width}
```


```{r P3cropMAP, eval=P3crop, map_plot=P3crop, fig.width=map_plot_width, fig.height= map_plot_height}
```



<!-- %
%   _      _                   _                _
%  | |    (_)__   __ ___  ___ | |_  ___    ___ | | __
%  | |    | |\ \ / // _ \/ __|| __|/ _ \  / __|| |/ /
%  | |___ | | \ V /|  __/\__ \| |_| (_) || (__ |   <
%  |_____||_|  \_/  \___||___/ \__|\___/  \___||_|\_\
%
% -->



```{r P3livestockTEXT, eval=P3livestock, short_text_ChartPage=P3livestock}
```

```{r P3livestockData,results='hide',cache=FALSE,eval=P3livestock}
```


```{r P3livestockTOPRIGHT, eval=P3livestock, top_right_minitable=P3livestock}
```


```{r P3livestockLEFT, eval=P3livestock, left_plot=P3livestock, fig.height=left_plot_height, fig.width=left_plot_width}
```

```{r P3livestockRIGHT, eval=P3livestock ,right_plot=P3livestock, fig.height=right_plot_height, fig.width=right_plot_width}
```



```{r P3livestockBOTTOM, eval=P3livestock, bottom_plot=P3livestock, fig.height=bottom_plot_height, fig.width=bottom_plot_width}
```




```{r P3livestockMAP, eval=P3crop, map_plot=P3crop, fig.width=map_plot_width, fig.height= map_plot_height}
```



<!-- %   _____  _       _                  _
%  |  ___|(_) ___ | |__    ___  _ __ (_)  ___  ___
%  | |_   | |/ __|| '_ \  / _ \| '__|| | / _ \/ __|
%  |  _|  | |\__ \| | | ||  __/| |   | ||  __/\__ \
%  |_|    |_||___/|_| |_| \___||_|   |_| \___||___/
% -->

```{r P3fisheriesTEXT, eval=P3fisheries, short_text_ChartPage=P3fisheries}
```

```{r P3fisheriesData,results='hide',cache=FALSE,eval=FALSE}
```


```{r P3fisheriesTOPRIGHT, eval=P3fisheries, top_right_plot=P3fisheries, fig.height=top_right_plot_height, fig.width=top_right_plot_width}
```


```{r P3fisheriesLEFT, eval=P3fisheries, left_plot=P3fisheries, fig.height=left_plot_height, fig.width=left_plot_width}
```

```{r P3fisheriesRIGHT, eval=P3fisheries ,right_plot=P3fisheries, fig.height=right_plot_height, fig.width=right_plot_width}
```


```{r P3fisheriesBOTTOM, eval=P3fisheries, bottom_plot=P3fisheries, fig.height=bottom_plot_height, fig.width=bottom_plot_width}
```


```{r P3fisheriesMAP, eval=P3fisheries, map_plot=P3fisheries, fig.width=map_plot_width, fig.height= map_plot_height}
```

<!-- %      _                 _               _  _                       _   _                    _
%     / \    __ _  _ __ (_)  ___  _   _ | || |_  _   _  _ __  __ _ | | | |_  _ __  __ _   __| |  ___
%    / _ \  / _` || '__|| | / __|| | | || || __|| | | || '__|/ _` || | | __|| '__|/ _` | / _` | / _ \
%   / ___ \| (_| || |   | || (__ | |_| || || |_ | |_| || |  | (_| || | | |_ | |  | (_| || (_| ||  __/
%  /_/   \_\\__, ||_|   |_| \___| \__,_||_| \__| \__,_||_|   \__,_||_|  \__||_|   \__,_| \__,_| \___|
%           |___/ -->



```{r P3tradeTEXT, eval=P3trade, short_text_ChartPage=P3trade}
```

```{r P3tradeData,results='hide',cache=FALSE,eval=P3trade}
```


```{r P3tradeTOPRIGHT, eval=P3trade, top_right_minitable=P3trade}
```


```{r P3tradeLEFT, eval=P3trade, left_plot=P3trade, fig.height=left_plot_height, fig.width=left_plot_width}
```

```{r P3tradeRIGHT, eval=P3trade ,right_plot=P3trade, fig.height=right_plot_height, fig.width=right_plot_width}
```


```{r P3tradeBOTTOM, eval=P3trade, bottom_plot=P3trade, fig.height=bottom_plot_height, fig.width=bottom_plot_width}
```


```{r P3tradeMAP, eval=P3trade, map_plot=P3trade, fig.width=map_plot_width, fig.height= map_plot_height}
```

