---
layout: "`r paste0("default_",region_to_report)`"
title:  Environment
group: "`r paste0("page_",region_to_report)`"
---

`r paste0('<div class="page-header"><h2 id="">',region_name,'</h2></div>')`


<!-- %
% PPPPPPPPPPPPPPPPP                                               tttt             444444444
% P::::::::::::::::P                                           ttt:::t            4::::::::4
% P::::::PPPPPP:::::P                                          t:::::t           4:::::::::4
% PP:::::P     P:::::P                                         t:::::t          4::::44::::4
%   P::::P     P:::::Paaaaaaaaaaaaa  rrrrr   rrrrrrrrr   ttttttt:::::ttttttt   4::::4 4::::4
%   P::::P     P:::::Pa::::::::::::a r::::rrr:::::::::r  t:::::::::::::::::t  4::::4  4::::4
%   P::::PPPPPP:::::P aaaaaaaaa:::::ar:::::::::::::::::r t:::::::::::::::::t 4::::4   4::::4
%   P:::::::::::::PP           a::::arr::::::rrrrr::::::rtttttt:::::::tttttt4::::444444::::444
%   P::::PPPPPPPPP      aaaaaaa:::::a r:::::r     r:::::r      t:::::t      4::::::::::::::::4
%   P::::P            aa::::::::::::a r:::::r     rrrrrrr      t:::::t      4444444444:::::444
%   P::::P           a::::aaaa::::::a r:::::r                  t:::::t                4::::4
%   P::::P          a::::a    a:::::a r:::::r                  t:::::t    tttttt      4::::4
% PP::::::PP        a::::a    a:::::a r:::::r                  t::::::tttt:::::t      4::::4
% P::::::::P        a:::::aaaa::::::a r:::::r                  tt::::::::::::::t    44::::::44
% P::::::::P         a::::::::::aa:::ar:::::r                    tt:::::::::::tt    4::::::::4
% PPPPPPPPPP          aaaaaaaaaa  aaaarrrrrrr                      ttttttttttt      4444444444
%
%


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% PART4 - Sustainability dimensions
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->



```{r setup-code-part4}
knitr::read_chunk(paste0(root.dir,"input/code/code_part4.R"))
```


```{r part4_setup, eval=include_part4}
```



<!-- %
%   _                       _
%  | |     __ _  _ __    __| |
%  | |    / _` || '_ \  / _` |
%  | |___| (_| || | | || (_| |
%  |_____|\__,_||_| |_| \__,_|
%
% -->



```{r P4landTEXT, eval=P4land, short_text_ChartPage=P4land}
```

```{r P4landData,results='hide'}
```


```{r P4landTOPRIGHT, eval=P4land, top_right_plot=P4land, fig.height=top_right_plot_height, fig.width=top_right_plot_width}
```


```{r P4landLEFT, eval=P4land, left_plot=P4land, fig.height=left_plot_height, fig.width=left_plot_width}
```

```{r P4landRIGHT, eval=P4land ,right_plot=P4land, fig.height=right_plot_height, fig.width=right_plot_width}
```


```{r P4landBOTTOM, eval=P4land, bottom_plot=P4land, fig.height=bottom_plot_height, fig.width=bottom_plot_width}
```


```{r P4landMAP, eval=P4land, map_plot=P4land, fig.width=map_plot_width, fig.height= map_plot_height}
```




<!-- %
%  __        __          _
%  \ \      / /   __ _  | |_    ___   _ __
%   \ \ /\ / /   / _` | | __|  / _ \ | '__|
%    \ V  V /   | (_| | | |_  |  __/ | |
%     \_/\_/     \__,_|  \__|  \___| |_|
% -->




```{r P4waterTEXT, eval=P4water, short_text_ChartPage=P4water}
```


```{r P4waterData, cache=FALSE,results='hide', eval=P4water}
```



```{r P4waterTOPRIGHT, eval=P4water, top_right_plot=P4water, fig.height=top_right_plot_height, fig.width=top_right_plot_width}
```


```{r P4waterLEFT, eval=P4water, left_plot=P4water, fig.height=left_plot_height, fig.width=left_plot_width}
```

```{r P4waterRIGHT, eval=P4water ,right_plot=P4water, fig.height=right_plot_height, fig.width=right_plot_width}
```


```{r P4waterBOTTOM, eval=P4water, bottom_plot=P4water, fig.height=bottom_plot_height, fig.width=bottom_plot_width}
```


```{r P4waterMAP, eval=P4water, map_plot=P4water, fig.width=map_plot_width, fig.height= map_plot_height}
```





<!-- %   _____
%  | ____|  _ __     ___   _ __    __ _   _   _
%  |  _|   | '_ \   / _ \ | '__|  / _` | | | | |
%  | |___  | | | | |  __/ | |    | (_| | | |_| |
%  |_____| |_| |_|  \___| |_|     \__, |  \__, |
%                                 |___/   |___/ -->



```{r P4energyTEXT, eval=P4energy, short_text_ChartPage=P4energy}
```


```{r P4energyData, cache=FALSE,results='hide', eval=P4energy}
```



```{r P4energyTOPRIGHT, eval=P4energy, top_right_plot=P4energy, fig.height=top_right_plot_height, fig.width=top_right_plot_width}
```


```{r P4energyLEFT, eval=P4energy, left_plot=P4energy, fig.height=left_plot_height, fig.width=left_plot_width}
```

```{r P4energyRIGHT, eval=P4energy ,right_plot=P4energy, fig.height=right_plot_height, fig.width=right_plot_width}
```


```{r P4energyBOTTOM, eval=P4energy, bottom_plot=P4energy, fig.height=bottom_plot_height, fig.width=bottom_plot_width}
```


```{r P4energyMAP, eval=P4energy, map_plot=P4energy, fig.width=map_plot_width, fig.height= map_plot_height}
```





<!-- %   _____                               _
%  |  ___|   ___    _ __    ___   ___  | |_   _ __   _   _
%  | |_     / _ \  | '__|  / _ \ / __| | __| | '__| | | | |
%  |  _|   | (_) | | |    |  __/ \__ \ | |_  | |    | |_| |
%  |_|      \___/  |_|     \___| |___/  \__| |_|     \__, |
%                                                    |___/ -->





```{r P4forestryTEXT, eval=P4forestry, short_text_ChartPage=P4forestry}
```

```{r P4forestryData,results='hide'}
```


```{r P4forestryTOPRIGHT, eval=P4forestry, top_right_plot=P4forestry, fig.height=top_right_plot_height, fig.width=top_right_plot_width}
```


```{r P4forestryLEFT, eval=P4forestry, left_plot=P4forestry, fig.height=left_plot_height, fig.width=left_plot_width}
```

```{r P4forestryRIGHT, eval=P4forestry ,right_plot=P4forestry, fig.height=right_plot_height, fig.width=right_plot_width}
```


```{r P4forestryBOTTOM, eval=P4forestry, bottom_plot=P4forestry, fig.height=bottom_plot_height, fig.width=bottom_plot_width}
```


```{r P4forestryMAP, eval=P4forestry, map_plot=P4forestry, fig.width=map_plot_width, fig.height= map_plot_height}
```





<!-- %    ____   _   _                       _                     _
%   / ___| | | (_)  _ __ ___     __ _  | |_    ___      ___  | |__     __ _   _ __     __ _    ___
%  | |     | | | | | '_ ` _ \   / _` | | __|  / _ \    / __| | '_ \   / _` | | '_ \   / _` |  / _ \
%  | |___  | | | | | | | | | | | (_| | | |_  |  __/   | (__  | | | | | (_| | | | | | | (_| | |  __/
%   \____| |_| |_| |_| |_| |_|  \__,_|  \__|  \___|    \___| |_| |_|  \__,_| |_| |_|  \__, |  \___|
%                                                                                     |___/ -->


```{r P4climateTEXT, eval=P4climate, short_text_ChartPage=P4climate}
```

```{r P4climateData,results='hide'}
```


```{r P4climateTOPRIGHT, eval=P4climate, top_right_plot=P4climate, fig.height=top_right_plot_height, fig.width=top_right_plot_width}
```


```{r P4climateLEFT, eval=P4climate, left_plot=P4climate, fig.height=left_plot_height, fig.width=left_plot_width}
```

```{r P4climateRIGHT, eval=P4climate ,right_plot=P4climate, fig.height=right_plot_height, fig.width=right_plot_width}
```


```{r P4climateBOTTOM, eval=P4climate, bottom_plot=P4climate, fig.height=bottom_plot_height, fig.width=bottom_plot_width}
```


```{r P4climateMAP, eval=P4climate, map_plot=P4climate, fig.width=map_plot_width, fig.height= map_plot_height}
```
