---
layout: "`r paste0("default_",region_to_report)`"
title:  The setting
group: "`r paste0("page_",region_to_report)`"
---

`r paste0('<div class="page-header"><h2 id="">',region_name,'</h2></div>')`




<!-- %
% PPPPPPPPPPPPPPPPP                                               tttt            1111111
% P::::::::::::::::P                                           ttt:::t           1::::::1
% P::::::PPPPPP:::::P                                          t:::::t          1:::::::1
% PP:::::P     P:::::P                                         t:::::t          111:::::1
%   P::::P     P:::::Paaaaaaaaaaaaa  rrrrr   rrrrrrrrr   ttttttt:::::ttttttt       1::::1
%   P::::P     P:::::Pa::::::::::::a r::::rrr:::::::::r  t:::::::::::::::::t       1::::1
%   P::::PPPPPP:::::P aaaaaaaaa:::::ar:::::::::::::::::r t:::::::::::::::::t       1::::1
%   P:::::::::::::PP           a::::arr::::::rrrrr::::::rtttttt:::::::tttttt       1::::l
%   P::::PPPPPPPPP      aaaaaaa:::::a r:::::r     r:::::r      t:::::t             1::::l
%   P::::P            aa::::::::::::a r:::::r     rrrrrrr      t:::::t             1::::l
%   P::::P           a::::aaaa::::::a r:::::r                  t:::::t             1::::l
%   P::::P          a::::a    a:::::a r:::::r                  t:::::t    tttttt   1::::l
% PP::::::PP        a::::a    a:::::a r:::::r                  t::::::tttt:::::t111::::::111
% P::::::::P        a:::::aaaa::::::a r:::::r                  tt::::::::::::::t1::::::::::1
% P::::::::P         a::::::::::aa:::ar:::::r                    tt:::::::::::tt1::::::::::1
% PPPPPPPPPP          aaaaaaaaaa  aaaarrrrrrr                      ttttttttttt  111111111111 -->


```{r setup-code-part1}
knitr::read_chunk(paste0(root.dir,"input/code/code_part1.R"))
```

```{r part1_setup, eval=include_part1}
```


<!-- %    ___                                  _ -->
<!-- %   / _ \  __   __   ___   _ __  __   __ (_)   ___  __      __ -->
<!-- %  | | | | \ \ / /  / _ \ | '__| \ \ / / | |  / _ \ \ \ /\ / / -->
<!-- %  | |_| |  \ V /  |  __/ | |     \ V /  | | |  __/  \ V  V / -->
<!-- %   \___/    \_/    \___| |_|      \_/   |_|  \___|   \_/\_/ -->
<!-- % -->


```{r P1overTEXT, eval=P1over, short_text_ChartPage=P1over}
```


```{r P1overData,results='hide', cache=FALSE}
```


```{r P1overTOPRIGHT, eval=P1over, top_right_plot=P1over, fig.height=top_right_plot_height, fig.width=top_right_plot_width}
```



```{r P1overLEFT, eval=P1over, left_plot=P1over, fig.height=left_plot_height, fig.width=left_plot_width}
```

```{r P1overRIGHT, eval=TRUE ,right_plot=P1over, fig.height=right_plot_height, fig.width=right_plot_width}
```


```{r P1overBOTTOM, eval=P1over, bottom_plot=P1over, fig.height=bottom_plot_height, fig.width=bottom_plot_width}
```


```{r P1overMAP, eval=P1over, map_plot=P1over, fig.width=map_plot_width, fig.height= map_plot_height}
```


<!-- %   _____
%  | ____|   ___    ___    _ __     ___    _ __ ___    _   _
%  |  _|    / __|  / _ \  | '_ \   / _ \  | '_ ` _ \  | | | |
%  | |___  | (__  | (_) | | | | | | (_) | | | | | | | | |_| |
%  |_____|  \___|  \___/  |_| |_|  \___/  |_| |_| |_|  \__, |
%                                                      |___/
% -->


```{r P1econTEXT, eval=P1econ, short_text_ChartPage=P1econ}
```

```{r P1econTOPRIGHT, eval=P1econ, top_right_plot=P1econ, fig.height=top_right_plot_height, fig.width=top_right_plot_width}
```


```{r P1econLEFT, eval=P1econ, left_plot=P1econ, fig.height=left_plot_height, fig.width=left_plot_width}
```

```{r P1econRIGHT, eval=P1econ ,right_plot=P1econ, fig.height=right_plot_height, fig.width=right_plot_width}
```


```{r P1econBOTTOM_data, cache=FALSE}
```



```{r P1econBOTTOM, eval=P1econ, bottom_plot=P1econ, fig.height=bottom_plot_height, fig.width=bottom_plot_width}
```


```{r P1econMAP, eval=P1econ, map_plot=P1econ, fig.width=map_plot_width, fig.height= map_plot_height}
```





<!-- %   _               _
%  | |       __ _  | |__     ___    _   _   _ __
%  | |      / _` | | '_ \   / _ \  | | | | | '__|
%  | |___  | (_| | | |_) | | (_) | | |_| | | |
%  |_____|  \__,_| |_.__/   \___/   \__,_| |_|
% -->


```{r P1laboTEXT, eval=P1labo, short_text_ChartPage=P1labo}
```

```{r P1laboTOPRIGHT, eval=P1labo, top_right_plot=P1labo, fig.height=top_right_plot_height, fig.width=top_right_plot_width}
```


```{r P1laboLEFT, eval=P1labo, left_plot=P1labo, fig.height=left_plot_height, fig.width=left_plot_width}
```

```{r P1laboRIGHT, eval=P1labo ,right_plot=P1labo, fig.height=right_plot_height, fig.width=right_plot_width}
```


```{r P1laboBOTTOM_data, cache=FALSE, results='hide'}
```



```{r P1laboBOTTOM, eval=P1labo, bottom_plot=P1labo, fig.height=bottom_plot_height, fig.width=bottom_plot_width}
```


```{r P1laboMAP, eval=P1labo, map_plot=P1labo, fig.width=map_plot_width, fig.height= map_plot_height}
```



<!-- %   ___                           _
%  |_ _|  _ __    _ __    _   _  | |_   ___
%   | |  | '_ \  | '_ \  | | | | | __| / __|
%   | |  | | | | | |_) | | |_| | | |_  \__ \
%  |___| |_| |_| | .__/   \__,_|  \__| |___/
%                |_|
% -->


```{r P1inputTEXT, eval=P1input, short_text_ChartPage=P1input}
```

```{r P1inputData,results='hide'}
```


```{r P1inputTOPRIGHT, eval=P1input, top_right_plot=P1input, fig.height=top_right_plot_height, fig.width=top_right_plot_width}
```


```{r P1inputLEFT, eval=P1input, left_plot=P1input, fig.height=left_plot_height, fig.width=left_plot_width}
```

```{r P1inputRIGHT, eval=P1input ,right_plot=P1input, fig.height=right_plot_height, fig.width=right_plot_width}
```


```{r P1inputBOTTOM, eval=P1input, bottom_plot=P1input, fig.height=bottom_plot_height, fig.width=bottom_plot_width}
```


```{r P1inputMAP, eval=P1input, map_plot=P1input, fig.width=map_plot_width, fig.height= map_plot_height}
```

<!-- %   ___                                _                                _
%  |_ _|  _ __   __   __   ___   ___  | |_   _ __ ___     ___   _ __   | |_
%   | |  | '_ \  \ \ / /  / _ \ / __| | __| | '_ ` _ \   / _ \ | '_ \  | __|
%   | |  | | | |  \ V /  |  __/ \__ \ | |_  | | | | | | |  __/ | | | | | |_
%  |___| |_| |_|   \_/    \___| |___/  \__| |_| |_| |_|  \___| |_| |_|  \__|
% -->


```{r P1investTEXT, eval=P1invest, short_text_ChartPage=P1invest}
```

```{r P1investData,results='hide', cache=FALSE}
```


```{r P1investTOPRIGHT, eval=P1invest, top_right_plot=P1invest, fig.height=top_right_plot_height, fig.width=top_right_plot_width}
```


```{r P1investLEFT, eval=P1invest, left_plot=P1invest, fig.height=left_plot_height, fig.width=left_plot_width}
```

```{r P1investRIGHT, eval=P1invest ,right_plot=P1invest, fig.height=right_plot_height, fig.width=right_plot_width}
```


```{r P1investBOTTOM, eval=P1invest, bottom_plot=P1invest, fig.height=bottom_plot_height, fig.width=bottom_plot_width}
```

```{r p1investMAPdata, results='hide', cache=FALSE}
```



```{r P1investMAP, eval=P1invest, map_plot=P1invest, fig.width=map_plot_width, fig.height= map_plot_height}
```

